before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/jf/main.go
    flags:
      - -o="#{bin}/jf"
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    tap:
      owner: WTFox
      name: homebrew-tap
    commit_author:
      name: A. Fox
      email: anthonyfox1988@gmail.com

    folder: Formula

    homepage: "https://afox.dev/posts/jsonfind"

    description: "jf prints out dotted paths to the given value for a given json file"

    license: "MIT"

    test: |
      system "#{bin}/jf --help"

    install: |
      bin.install "jf"
